%%{init: {
  'theme': 'default',
  'flowchart': { 'htmlLabels': false, 'useMaxWidth': false },
  'scale': 2
}}%%
graph LR

ElectronMicroscopy["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/Electron_microscope-01.png' width='100'/><br/>Electron Microscopy</div>"]
ControlComputer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/desktop.png' width='100'/><br/>Control Computer</div>"]
WorkstationComputer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/desktop.png' width='100'/><br/>Workstation Computer</div>"]


ElectronMicroscopy --> ControlComputer
ControlComputer --> |SMB Mount| DataFedClient
subgraph DataFedClient["DataFed Client"]
    DataFedContainer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/python.png' width='100'/><br/>DataFed Python Container</div>"]
    MetadataExtractor[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/github.svg' width='100'/><br/>Metadata Extractor</div>]
    GlobusConnectPersonal[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Connect Personal</div>]
    DataFedContainer --> MetadataExtractor
    DataFedContainer --> GlobusConnectPersonal
end

subgraph DataFedCoreService["DataFed Core Service"]
    DataFedMetadataDatabase[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/database.svg' width='100'/><br/>DataFed Metadata Database</div>]
    DatafedWebUI[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/webpage.svg' width='100'/><br/>Datafed Web UI</div>]
    DataFedMetadataDatabase --> DatafedWebUI
end

MetadataExtractor --> DataFedMetadataDatabase

GlobusConnectPersonal --> GlobusDataTransferNode

subgraph DataFedRepository["DataFed Repository"]
    GlobusDataTransferNode[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Data Transfer Node</div>]
    DataFedRepositoryContainer[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/docker.svg' width='100'/><br/>DataFed Repository Container</div>]
    ParallelFileSystem[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/pfs.svg' width='100'/><br/>Parallel File System</div>]
    GlobusDataTransferNode <--> DataFedRepositoryContainer
    DataFedRepositoryContainer <--> ParallelFileSystem
end

subgraph DataFedClient2["DataFed Client"]
    DataFedContainer2[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/docker.svg' width='100'/><br/>DataFed Python Container</div>]
    DataFedContainer2 --> DataFedMetadataDatabase
    GlobusConnectPersonal2[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Connect Personal</div>]
    DataFedContainer2 --> GlobusConnectPersonal2
    GlobusDataTransferNode --> GlobusConnectPersonal2
    DatafedWebUI --> GlobusDataTransferNode
end

WorkstationComputer --> DataFedClient2

---

%%{init: {
  'theme': 'default',
  'flowchart': { 'htmlLabels': false, 'useMaxWidth': false },
  'scale': 2
}}%%
graph LR

ElectronMicroscopy["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/Electron_microscope-01.png' width='100'/><br/>Electron Microscopy</div>"]
ControlComputer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/desktop.png' width='100'/><br/>Control Computer</div>"]
WorkstationComputer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/desktop.png' width='100'/><br/>Workstation Computer</div>"]


ElectronMicroscopy --> ControlComputer
ControlComputer --> |SMB Mount| DataFedClient
subgraph DataFedClient["DataFed Client"]
    DataFedContainer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/python.png' width='100'/><br/>DataFed Python Container</div>"]
    MetadataExtractor[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/github.svg' width='100'/><br/>Metadata Extractor</div>]
    GlobusConnectPersonal[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Connect Personal</div>]
    DataFedContainer --> MetadataExtractor
    DataFedContainer --> GlobusConnectPersonal
end

subgraph DataFedCoreService["DataFed Core Service"]
    DataFedMetadataDatabase[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/database.svg' width='100'/><br/>DataFed Metadata Database</div>]
    DatafedWebUI[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/webpage.svg' width='100'/><br/>Datafed Web UI</div>]
    DataFedMetadataDatabase --> DatafedWebUI
end

MetadataExtractor --> DataFedMetadataDatabase

GlobusConnectPersonal --> GlobusDataTransferNode

subgraph DataFedRepository["DataFed Repository"]
    GlobusDataTransferNode[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Data Transfer Node</div>]
    DataFedRepositoryContainer[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/docker.svg' width='100'/><br/>DataFed Repository Container</div>]
    ParallelFileSystem[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/pfs.svg' width='100'/><br/>Parallel File System</div>]
    GlobusDataTransferNode <--> DataFedRepositoryContainer
    DataFedRepositoryContainer <--> ParallelFileSystem
end

subgraph DataFedClient2["DataFed Client"]
    DataFedContainer2[<div style='opacity:0; text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/docker.svg' width='100'/><br/>DataFed Python Container</div>]
    DataFedContainer2 --> DataFedMetadataDatabase
    GlobusConnectPersonal2[<div style='opacity:0; text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Connect Personal</div>]
    DataFedContainer2 --> GlobusConnectPersonal2
    GlobusDataTransferNode --> GlobusConnectPersonal2
    DatafedWebUI --> GlobusDataTransferNode
end

WorkstationComputer --> DataFedClient2

classDef invisible fill-opacity:0, stroke-opacity:0, color:#ffffff, stroke:#ffffff, stroke-width:0;
linkStyle 9,10,11 stroke:#ffffff,stroke-opacity:0
classDef invisible fill-opacity:0, stroke-opacity:0, color:#ffffff, stroke:#ffffff, stroke-width:0;

---

%%{init: {
  'theme': 'default',
  'flowchart': { 'htmlLabels': false, 'useMaxWidth': false },
  'scale': 2
}}%%
graph LR

ElectronMicroscopy["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/Electron_microscope-01.png' width='100'/><br/>Electron Microscopy</div>"]
ControlComputer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/desktop.png' width='100'/><br/>Control Computer</div>"]
WorkstationComputer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/desktop.png' width='100'/><br/>Workstation Computer</div>"]


ElectronMicroscopy --> ControlComputer
ControlComputer --> |SMB Mount| DataFedClient
subgraph DataFedClient["DataFed Client"]
    DataFedContainer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/python.png' width='100'/><br/>DataFed Python Container</div>"]
    MetadataExtractor[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/github.svg' width='100'/><br/>Metadata Extractor</div>]
    GlobusConnectPersonal[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Connect Personal</div>]
    DataFedContainer --> MetadataExtractor
    DataFedContainer --> GlobusConnectPersonal
end

subgraph DataFedCoreService["DataFed Core Service"]
    DataFedMetadataDatabase[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/database.svg' width='100'/><br/>DataFed Metadata Database</div>]
    DatafedWebUI[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/webpage.svg' width='100'/><br/>Datafed Web UI</div>]
    DataFedMetadataDatabase --> DatafedWebUI
end

MetadataExtractor --> DataFedMetadataDatabase

GlobusConnectPersonal --> GlobusDataTransferNode

subgraph DataFedRepository["DataFed Repository"]
    GlobusDataTransferNode[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Data Transfer Node</div>]
    DataFedRepositoryContainer[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/docker.svg' width='100'/><br/>DataFed Repository Container</div>]
    ParallelFileSystem[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/pfs.svg' width='100'/><br/>Parallel File System</div>]
    GlobusDataTransferNode <--> DataFedRepositoryContainer
    DataFedRepositoryContainer <--> ParallelFileSystem
end

subgraph DataFedClient2["DataFed Client"]
    DataFedContainer2[<div style='opacity:0; text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/docker.svg' width='100'/><br/>DataFed Python Container</div>]
    DataFedContainer2 --> DataFedMetadataDatabase
    GlobusConnectPersonal2[<div style='opacity:0; text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Connect Personal</div>]
    DataFedContainer2 --> GlobusConnectPersonal2
    GlobusDataTransferNode --> GlobusConnectPersonal2
    DatafedWebUI --> GlobusDataTransferNode
end

WorkstationComputer --> DataFedClient2

classDef invisible fill-opacity:0, stroke-opacity:0, color:#ffffff, stroke:#ffffff, stroke-width:0;
linkStyle 9,10,11,8,6,5 stroke:#ffffff,stroke-opacity:0

---

%%{init: {
  'theme': 'default',
  'flowchart': { 'htmlLabels': false, 'useMaxWidth': false },
  'scale': 2
}}%%
graph LR

ElectronMicroscopy["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/Electron_microscope-01.png' width='100'/><br/>Electron Microscopy</div>"]
ControlComputer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/desktop.png' width='100'/><br/>Control Computer</div>"]
WorkstationComputer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/desktop.png' width='100'/><br/>Workstation Computer</div>"]


ElectronMicroscopy --> ControlComputer
ControlComputer --> |SMB Mount| DataFedClient
subgraph DataFedClient["DataFed Client"]
    DataFedContainer["<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/python.png' width='100'/><br/>DataFed Python Container</div>"]
    MetadataExtractor[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/github.svg' width='100'/><br/>Metadata Extractor</div>]
    GlobusConnectPersonal[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Connect Personal</div>]
    DataFedContainer --> MetadataExtractor
    DataFedContainer --> GlobusConnectPersonal
end

subgraph DataFedCoreService["DataFed Core Service"]
    DataFedMetadataDatabase[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/database.svg' width='100'/><br/>DataFed Metadata Database</div>]
    DatafedWebUI[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/webpage.svg' width='100'/><br/>Datafed Web UI</div>]
    DataFedMetadataDatabase --> DatafedWebUI
end

MetadataExtractor --> DataFedMetadataDatabase

GlobusConnectPersonal --> GlobusDataTransferNode

subgraph DataFedRepository["DataFed Repository"]
    GlobusDataTransferNode[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Data Transfer Node</div>]
    DataFedRepositoryContainer[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/docker.svg' width='100'/><br/>DataFed Repository Container</div>]
    ParallelFileSystem[<div style='text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/pfs.svg' width='100'/><br/>Parallel File System</div>]
    GlobusDataTransferNode <--> DataFedRepositoryContainer
    DataFedRepositoryContainer <--> ParallelFileSystem
end

subgraph DataFedClient2["DataFed Client"]
    DataFedContainer2[<div style='opacity:0; text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/docker.svg' width='100'/><br/>DataFed Python Container</div>]
    DataFedContainer2 --> DataFedMetadataDatabase
    GlobusConnectPersonal2[<div style='opacity:0; text-align:center'><img src='https://raw.githubusercontent.com/jagar2/SSMC-CI-Madison-5-20-2025/refs/heads/main/public/icon/globus.png' width='100'/><br/>Globus Connect Personal</div>]
    DataFedContainer2 --> GlobusConnectPersonal2
    GlobusDataTransferNode --> GlobusConnectPersonal2
    DatafedWebUI --> GlobusDataTransferNode
end

WorkstationComputer --> DataFedClient2

classDef invisible fill-opacity:0, stroke-opacity:0, color:#ffffff, stroke:#ffffff, stroke-width:0;
linkStyle 9,10,11,8,6,5,1 stroke:#ffffff,stroke-opacity:0